version: '3'

services:

  app:
    build:
      context: ./node
    image: nginx-node-app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["node", "index.js"]
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_volumes

  nginx:
    build:
      context: ./nginx
    image: nginx-node-nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network

  db:
    build:
      context: ./mysql
    image: nginx-node-db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
